baseURL = 'https://admingit2025.github.io/www'
languageCode = 'zh-cn'
title = 'My Hugo Blog'
theme = 'PaperMod'

# 启用 Git Info
enableGitInfo = true

[params]
  # 网站描述
  description = "我的个人博客"
  
  # 作者信息
  author = "Your Name"
  
  # 默认主题模式
  defaultTheme = "auto"
  
  # 显示分享按钮
  ShowShareButtons = true
  
  # 显示文章阅读时间
  ShowReadingTime = true
  
  # 显示目录
  ShowToc = true
  
  # 显示面包屑导航
  ShowBreadCrumbs = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
    
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 20
    
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 30
    
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 40 