baseURL = 'https://www.git.edu.kg'
languageCode = 'zh-cn'
title = '科技观察'
theme = 'PaperMod'

# 启用 emoji 支持
enableEmoji = true

# 启用 robots.txt
enableRobotsTXT = true

# 启用 Git Info
enableGitInfo = true
[pagination]
  pagerSize = 10
summaryLength = 70

[params]
  # 网站描述
  description = "关注前沿科技发展，分享最新科技突破"
  
  # 作者设置
  author = "科技观察团队"
  
  # 默认主题模式 (auto, light, dark)
  defaultTheme = "auto"
  
  # 是否显示阅读时间
  ShowReadingTime = true
  
  # 是否显示分享按钮
  ShowShareButtons = true
  
  # 是否显示文章目录
  ShowToc = true
  
  # 是否自动展开目录
  TocOpen = true

  # 主页设置
  [params.homeInfoParams]
    Title = "欢迎来到科技观察"
    Content = "我们关注全球前沿科技发展，为您带来最新科技突破和创新资讯。"

  # 社交链接
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/your-github"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/your-twitter"

  # 搜索功能
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

# 菜单配置
[menu]
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 30

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    style = "monokai"
  [markup.goldmark.renderer]
    unsafe = true # 允许 HTML 标签 