baseURL = 'https://admingit2025.github.io/www'
languageCode = 'zh-cn'
title = 'My Hugo Blog'
theme = 'PaperMod'

# 启用 Git Info
enableGitInfo = true
[pagination]
  pagerSize = 10
summaryLength = 70

[params]
  # 网站描述
  description = "我的个人博客"
  
  # 作者信息
  author = "Your Name"
  
  # Analytics
  googleAnalytics = ""
  
  # 默认主题模式
  defaultTheme = "auto"
  
  # 显示分享按钮
  ShowShareButtons = true
  
  # 显示文章阅读时间
  ShowReadingTime = true
  
  # 显示目录
  ShowToc = true
  
  # 显示面包屑导航
  ShowBreadCrumbs = true
  
  # 显示代码复制按钮
  ShowCodeCopyButtons = true
  
  # 显示文章字数统计
  ShowWordCount = true
  
  # 显示最后修改时间
  ShowPostNavLinks = true
  
  # 启用搜索功能
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

# 社交链接
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/admingit2025"

[[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/yourusername"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
    
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 20
    
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 30
    
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 40

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    style = "monokai"
  [markup.goldmark.renderer]
    unsafe = true # 允许 HTML 标签 